### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by justanhduc** [pytorch/nestedtensor#13]
Currently I cannot install the package with MSVC toolset 14.11.25503 on Windows 10, Python 3.7 Anaconda. The command causing error is [here](https://gist.github.com/justanhduc/72fa984cb62f7133c72110727ef389a3).

**Comment by cpuhrsch** [comment]
Hello @justanhduc - for now we don't test for explicit Windows coverage and don't maintain it. This will be rolled out incrementally.
