### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by justanhduc** [pytorch/nestedtensor#3]
================================================= test session starts =================================================
platform win32 -- Python 3.7.4, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\justanhduc\Downloads\nestedtensor
plugins: arraydiff-0.3, doctestplus-0.4.0, openfiles-0.4.0, remotedata-0.3.2
collected 23 items

test\test_nested_tensor_autograd.py .                                                                            [  4%]
test\test_nested_tensor_class.py .....F.F...                                                                     [ 52%]
test\test_nested_tensor_functional.py ...                                                                        [ 65%]
test\test_nested_tensor_masking.py ....                                                                          [ 82%]
test\test_nested_tensor_tensorwise.py ...F                                                                       [100%]

====================================================== FAILURES =======================================================
__________________________________________ TestNestedTensor.test_nested_dim ___________________________________________

self = <test_nested_tensor_class.TestNestedTensor testMethod=test_nested_dim>

    def test_nested_dim(self):
>       nt = torch.nested_tensor([torch.tensor(3)])

test\test_nested_tensor_class.py:99:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\ProgramData\Anaconda3\lib\site-packages\nestedtensor\nested\creation.py:102: in nested_tensor
    buffer_ = _create_buffer(data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

data = [tensor(3)]

    def _create_buffer(data):
        if isinstance(data, torch.Tensor):
            return data.flatten()  # This data will be copied implicitly via cat
>       return torch.cat([_create_buffer(data_) for data_ in data], dim=0)
E       RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

C:\ProgramData\Anaconda3\lib\site-packages\nestedtensor\nested\creation.py:77: RuntimeError
______________________________________ TestNestedTensor.test_scalar_constructor _______________________________________

self = <test_nested_tensor_class.TestNestedTensor testMethod=test_scalar_constructor>

    def test_scalar_constructor(self):
>       dim_one_nested_tensor = torch.nested_tensor([1.0])

test\test_nested_tensor_class.py:57:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\ProgramData\Anaconda3\lib\site-packages\nestedtensor\nested\creation.py:102: in nested_tensor
    buffer_ = _create_buffer(data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

data = [tensor(1.)]

    def _create_buffer(data):
        if isinstance(data, torch.Tensor):
            return data.flatten()  # This data will be copied implicitly via cat
>       return torch.cat([_create_buffer(data_) for data_ in data], dim=0)
E       RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

C:\ProgramData\Anaconda3\lib\site-packages\nestedtensor\nested\creation.py:77: RuntimeError
_____________________________________ TestTensorWise.test_tensorwise_tensor_kwarg _____________________________________

self = <test_nested_tensor_tensorwise.TestTensorWise testMethod=test_tensorwise_tensor_kwarg>

    def test_tensorwise_tensor_kwarg(self):

        @nestedtensor.tensorwise(unbind_args=['out'])
        def simple_fn(t1, t2, t3=None):
            result = t1 * 2 + t2
            if t3 is not None:
                result = result + t3
            return result

        a = torch.tensor([1, 2])
        b = torch.tensor([7, 8])
        nt1 = torch.nested_tensor([a, b])
        nt2 = torch.nested_tensor([b, a])
>       c1 = simple_fn(a, b, t3=torch.tensor((0.5, 0.7)))

test\test_nested_tensor_tensorwise.py:65:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\ProgramData\Anaconda3\lib\site-packages\nestedtensor\nested\utils.py:190: in decorator
    return f(*_args, **_kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

t1 = tensor([1, 2]), t2 = tensor([7, 8]), t3 = tensor([0.5000, 0.7000])

    @nestedtensor.tensorwise(unbind_args=['out'])
    def simple_fn(t1, t2, t3=None):
        result = t1 * 2 + t2
        if t3 is not None:
>           result = result + t3
E           RuntimeError: expected device cpu and dtype Float but got device cpu and dtype Long

test\test_nested_tensor_tensorwise.py:58: RuntimeError
============================================ 3 failed, 20 passed in 2.31s =============================================

There are a bunch of failing tests due to the creation from scalars. I am not sure if you want to fix it on the API side or the test side so I will leave it to you. The last one is simply a typo so I can make a PR for that if you need.

**Comment by cpuhrsch** [comment]
Thank you @justanhduc! This repository is still work in progress, so you can expect something like this to happen again. I'll fix the test in question.

**Comment by cpuhrsch** [comment]
We just fixed this, I think. Please reopen if that's not the case.
