### ISSUE TITLE
ModuleNotFoundError: No module named 'nestedtensor.extension'

### ISSUE THREAD

**Issue by lurenyi233** [pytorch/nestedtensor#340]
Dear, when I  `import nestedtensor`

I met this problem:

> ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-b671cda544ae> in <module>
----> 1 import nestedtensor
> D:\Program_Files\ANACONDA\lib\site-packages\nestedtensor\__init__.py in <module>
      2 if getattr(torch, "__IS_MONKEY_PATCHED_BY_NESTED_TENSOR", None) is None:
      3     from .nested.monkey_patch import monkey_patch
----> 4     torch = monkey_patch(torch)
      5 # Confirm that this function was only applied once
      6 assert torch.__IS_MONKEY_PATCHED_BY_NESTED_TENSOR == 1
> D:\Program_Files\ANACONDA\lib\site-packages\nestedtensor\nested\monkey_patch.py in monkey_patch(module)
     39     import os
     40     DEBUG = int(os.getenv("DEBUG", 0))
---> 41     from . import utils
     42     from .nested import NestedTensor
     43     from . import creation
> D:\Program_Files\ANACONDA\lib\site-packages\nestedtensor\nested\utils.py in <module>
      6 import os
      7 
----> 8 from .nested import NestedTensor
      9 from . import creation
     10 from . import bufferimpl
> D:\Program_Files\ANACONDA\lib\site-packages\nestedtensor\nested\nested.py in <module>
      9 from . import utils
     10 
---> 11 **from nestedtensor.extension import _lazy_import**
     12 
     13 # Set this flag to true, if you want to enable additional verifications.

> **ModuleNotFoundError: No module named 'nestedtensor.extension'**

1. My python version is 3.8, and I tried to download this nestedtensor whl.

0.1.1 | 3.8 | CPU-only | torch, nestedtensor, torchvision
-- | -- | -- | --

But I got `This XML file does not appear to have any style information associated with it. The document tree is shown below.`
So I installed nestedtensor of the 3.7 version and met this problem.

2. Then I uninstalled it, and installed whl. file of nestedtensor from [Python Package Index (PyPI) ](https://pypi.org/project/nestedtensor/#files) , but still have this problem.

Does this problem caused by my python version? wish you could help me.

**Comment by cpuhrsch** [comment]
Hello @lurenyi233,

Thank you for posting this issue! The wheel on pypi associated to this package is currently defunct. Let me fix this. In the meantime, please see the installation instructions at the top of [the whirlwind tutorial](https://colab.research.google.com/github/pytorch/nestedtensor/blob/master/tutorials/notebooks/basic.ipynb). 

To help you better, what is the usecase you'd like to apply nestedtensor to?

Thanks
Christian

**Comment by lurenyi233** [comment]
> Christian

Dear Christian,

Thank you for your reply. I also have tried "the whirlwind tutorial", and I found I can't successfully install packages in the setup by "! pip install".
I wish I can use nestedtensor as I am studying the "[Spatial Pyramid Pooling](https://arxiv.org/abs/1406.4729)" method, in this method we want to put tensors of different shapes into one dataloader and shuffle them, so I can take out a mixture batch from the dataloader.
As you may know, tensors in different shapes can not be stacked to be a bigger tensor. I wish nestedtensor can help me to mask these tensors and then I can make them into one batch.

**Comment by cpuhrsch** [comment]
@lurenyi233,

based on your stacktrace it looks like you still have an older version of nestedtensor installed (the monkey patching logic was long removed). Can you try removing all packages and installing again or using a new conda environment etc. if you haven't already?

Thanks,
Christian

**Comment by lurenyi233** [comment]
Dear Christian,

Sorry for my late reply. it's true that I use the Windows system. I also found I can't install the package by using
`conda install nestedtensor`

I have run the collect_env file and it shows that.
> OS: Microsoft Windows 10
> [conda] pytorch                   1.7.0  
> Python version: 3.8 (64-bit runtime)

If I understand correctly, I can't use this package in a Windows environment right?
Thank you for your help!

**Comment by cpuhrsch** [comment]
Hello @lurenyi233,

Yes, unfortunately at this time you can't use nestedtensor in Windows. It also is not available on conda yet. Please stay tuned as we roll out packages for more platforms, but I can't give a timeline on when it'll be available on Windows.

Thanks,
Christian
